/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymangementsystem.view.Main.MainMenu.TaskPanePanels;

import javax.swing.JDesktopPane;
import librarymangementsystem.view.Borrower.Borrower;
import librarymangementsystem.view.Borrower.BorrowerDetails;
import librarymangementsystem.view.Main.MainMenu.MainPage;

/**
 *
 * @author Gamindu
 */
public class AddBorrower1 extends javax.swing.JPanel {

    private MainPage mainPage;
    private JDesktopPane desktop;
    private Borrower borrower;
    private BorrowerDetails borrowerDetails;
    /**
     * Creates new form testPanelForm
     */
    
    public  AddBorrower1(MainPage mainPage, JDesktopPane desktop) {
        this.mainPage = mainPage;
        this.desktop = desktop;

   
        initComponents();
        
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("New Borrower");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search Borrower");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
   if (borrower == null) {
           borrower = new Borrower();
            desktop.add(borrower);
            borrower.setVisible(true);
            desktop.setComponentZOrder(borrower, JDesktopPane.DEFAULT_LAYER);
        } else {
         
            desktop.remove(borrower);
            desktop.add(borrower);
            borrower.setVisible(true);
            desktop.setComponentZOrder(borrower, JDesktopPane.DEFAULT_LAYER);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
   if (borrowerDetails == null) {
           borrowerDetails = new BorrowerDetails();
            desktop.add(borrowerDetails);
            borrowerDetails.setVisible(true);
            desktop.setComponentZOrder(borrowerDetails, JDesktopPane.DEFAULT_LAYER);
        } else {
         
            desktop.remove(borrowerDetails);
            desktop.add(borrowerDetails);
            borrowerDetails.setVisible(true);
            desktop.setComponentZOrder(borrowerDetails, JDesktopPane.DEFAULT_LAYER);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    private static class Addborrower {

        public Addborrower() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
