/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymangementsystem.view.Main.MainMenu.TaskPanePanels;

import javax.swing.JDesktopPane;
import librarymangementsystem.view.Item.Item;
import librarymangementsystem.view.Item.ItemDetails;
import librarymangementsystem.view.Main.MainMenu.MainPage;



public class AddItem1 extends javax.swing.JPanel {
    
     private MainPage mainPage;
     private JDesktopPane desktop;
    private Item item;
   
    private ItemDetails itemDetails;
/**

    /**
     * Creates new form AddItem
     */
    public AddItem1(MainPage mainPage, JDesktopPane desktop) {
        initComponents();
        
                
        this.mainPage = mainPage;
        this.desktop = desktop;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("New Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if (item == null) {
          item = new Item();
            desktop.add(item);
           item.setVisible(true);
            desktop.setComponentZOrder(item, JDesktopPane.DEFAULT_LAYER);
        } else {
         
            desktop.remove(item);
            desktop.add(item);
           item.setVisible(true);
            desktop.setComponentZOrder(item, JDesktopPane.DEFAULT_LAYER);
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

          if (itemDetails == null) {
          itemDetails   = new ItemDetails();
            desktop.add(itemDetails  );
           itemDetails  .setVisible(true);
            desktop.setComponentZOrder(itemDetails  , JDesktopPane.DEFAULT_LAYER);
        } else {
         
            desktop.remove(itemDetails  );
            desktop.add(itemDetails  );
           itemDetails  .setVisible(true);
            desktop.setComponentZOrder(itemDetails  , JDesktopPane.DEFAULT_LAYER);
        }  
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
