/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymangementsystem.view.Main.MainMenu;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import librarymangementsystem.view.Main.MainMenu.TaskPanePanels.AddBorrower1;
import librarymangementsystem.view.Main.MainMenu.TaskPanePanels.AddItem1;
import librarymangementsystem.view.Main.MainMenu.TaskPanePanels.AddUser1;
import librarymangementsystem.view.Main.MainMenu.TaskPanePanels.LendItem1;
import librarymangementsystem.view.Main.MainMenu.TaskPanePanels.Reports1;

/**
 *
 * @author Gamindu
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    
        public static int userid;

     public MainPage(int userid) {
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        jDesktopPane.setSize(Toolkit.getDefaultToolkit().getScreenSize().width-115,Toolkit.getDefaultToolkit().getScreenSize().height);
        jDesktopPane.setLayer(backgroundImageLabel, jDesktopPane.DEFAULT_LAYER);
        backgroundImageLabel.setSize(Toolkit.getDefaultToolkit().getScreenSize().width-135,Toolkit.getDefaultToolkit().getScreenSize().height);
        ImageIcon background ;
        background = new ImageIcon(new ImageIcon(".\\src\\librarymangementsystem\\view\\Main\\MainMenu\\floral_powerpoint_background_by_kampinis-d6w27ep.jpg").getImage().getScaledInstance(backgroundImageLabel.getSize().width-145, backgroundImageLabel.getSize().height-60, Image.SCALE_SMOOTH));
        backgroundImageLabel.setLocation(0,0);
        backgroundImageLabel.setIcon(background);
        jPanel1.setLocation(0,0);
        jDesktopPane.setLocation(250, 0);
        
        this.userid = userid;
        
        
        jXLendItemTaskPane.add(new LendItem1(this,jDesktopPane,userid));
        jXAddBorrowerTaskPane.add(new AddBorrower1(this,jDesktopPane));
        jXAddItemTaskPane.add(new AddItem1(this,jDesktopPane));
        jXAddUserTaskPane.add(new AddUser1(this,jDesktopPane));
        jXReportsTaskPane.add(new Reports1(this, jDesktopPane));
 
        

        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        backgroundImageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jXLendItemTaskPane = new org.jdesktop.swingx.JXTaskPane();
        jXAddBorrowerTaskPane = new org.jdesktop.swingx.JXTaskPane();
        jXAddItemTaskPane = new org.jdesktop.swingx.JXTaskPane();
        jXReportsTaskPane = new org.jdesktop.swingx.JXTaskPane();
        jXAddUserTaskPane = new org.jdesktop.swingx.JXTaskPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addComponent(backgroundImageLabel)
                .addGap(0, 501, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addComponent(backgroundImageLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane.setLayer(backgroundImageLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 0));

        jXLendItemTaskPane.setToolTipText("");
        jXLendItemTaskPane.setTitle("Lend Item");
        jXLendItemTaskPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jXLendItemTaskPaneMouseMoved(evt);
            }
        });
        jXLendItemTaskPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXLendItemTaskPaneMouseEntered(evt);
            }
        });

        jXAddBorrowerTaskPane.setTitle(" Brrower");
        jXAddBorrowerTaskPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXAddBorrowerTaskPaneMouseEntered(evt);
            }
        });

        jXAddItemTaskPane.setTitle("Item");
        jXAddItemTaskPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXAddItemTaskPaneMouseEntered(evt);
            }
        });

        jXReportsTaskPane.setTitle("Reports");
        jXReportsTaskPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXReportsTaskPaneMouseEntered(evt);
            }
        });

        jXAddUserTaskPane.setTitle("User");
        jXAddUserTaskPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXAddUserTaskPaneMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXReportsTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXAddUserTaskPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLendItemTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jXAddItemTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXAddBorrowerTaskPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLendItemTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXAddBorrowerTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXAddItemTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXAddUserTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXReportsTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(635, 635, 635))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXAddUserTaskPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXAddUserTaskPaneMouseEntered
        jXAddBorrowerTaskPane.setCollapsed(true);
        jXLendItemTaskPane.setCollapsed(true);
        jXAddItemTaskPane.setCollapsed(true);

        jXAddUserTaskPane.setCollapsed(false);
        jXReportsTaskPane.setCollapsed(true);
    }//GEN-LAST:event_jXAddUserTaskPaneMouseEntered

    private void jXReportsTaskPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXReportsTaskPaneMouseEntered
        jXAddBorrowerTaskPane.setCollapsed(true);
        jXLendItemTaskPane.setCollapsed(true);
        jXAddItemTaskPane.setCollapsed(true);

        jXAddUserTaskPane.setCollapsed(true);
        jXReportsTaskPane.setCollapsed(false);// TODO add your handling code here:
    }//GEN-LAST:event_jXReportsTaskPaneMouseEntered

    private void jXAddItemTaskPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXAddItemTaskPaneMouseEntered
        jXAddBorrowerTaskPane.setCollapsed(true);
        jXLendItemTaskPane.setCollapsed(true);
        jXAddItemTaskPane.setCollapsed(false);
 
        jXAddUserTaskPane.setCollapsed(true);
        jXReportsTaskPane.setCollapsed(true);// TODO add your handling code here:
    }//GEN-LAST:event_jXAddItemTaskPaneMouseEntered

    private void jXAddBorrowerTaskPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXAddBorrowerTaskPaneMouseEntered
        jXAddBorrowerTaskPane.setCollapsed(false);
        jXLendItemTaskPane.setCollapsed(true);
        jXAddItemTaskPane.setCollapsed(true);
       
        jXAddUserTaskPane.setCollapsed(true);
        jXReportsTaskPane.setCollapsed(true);
    }//GEN-LAST:event_jXAddBorrowerTaskPaneMouseEntered

    private void jXLendItemTaskPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLendItemTaskPaneMouseEntered
        jXAddBorrowerTaskPane.setCollapsed(true);
        jXLendItemTaskPane.setCollapsed(false);
        jXAddItemTaskPane.setCollapsed(true);
 
        jXAddUserTaskPane.setCollapsed(true);
        jXReportsTaskPane.setCollapsed(true);

    }//GEN-LAST:event_jXLendItemTaskPaneMouseEntered

    private void jXLendItemTaskPaneMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXLendItemTaskPaneMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jXLendItemTaskPaneMouseMoved
 
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(new WindowsLookAndFeel());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new MainPage(userid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImageLabel;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXTaskPane jXAddBorrowerTaskPane;
    private org.jdesktop.swingx.JXTaskPane jXAddItemTaskPane;
    private org.jdesktop.swingx.JXTaskPane jXAddUserTaskPane;
    private org.jdesktop.swingx.JXTaskPane jXLendItemTaskPane;
    private org.jdesktop.swingx.JXTaskPane jXReportsTaskPane;
    // End of variables declaration//GEN-END:variables
}
